#!/bin/bash
# 启动故障注入测试环境
# Start fault injection test environment

echo "=== 🚀 AUV故障注入测试环境 / Fault Injection Test Environment ==="
echo ""
echo "📋 启动步骤 / Startup Steps:"
echo ""
echo "1️⃣  新终端启动Gazebo:"
echo "   source ~/.zshrc"
echo "   ros2 launch uuv_gazebo_worlds ocean_waves.launch"
echo ""
echo "2️⃣  新终端启动机器人:"
echo "   source ~/.zshrc"
echo "   ros2 launch uuv_descriptions upload_rexrov_default.launch.py mode:=default x:=0 y:=0 z:=-20 namespace:=rexrov gazebo_namespace:=\"''\""
echo ""
echo "3️⃣  新终端启动推进器:"
echo "   source ~/.zshrc"
echo "   ros2 launch uuv_thruster_manager thruster_manager.launch model_name:=rexrov"
echo ""
echo "4️⃣  新终端启动命令转换:"
echo "   source ~/.zshrc"
echo "   python3 ~/ros2_ws/cmd_vel_to_wrench_simple.py"
echo ""
echo "5️⃣  新终端启动键盘控制:"
echo "   source ~/.zshrc"
echo "   python3 ~/ros2_ws/simple_teleop.py"
echo ""
echo "6️⃣  新终端启动故障注入器:"
echo "   source ~/.zshrc"
echo "   python3 ~/ros2_ws/fault_test/scripts/fault_injector_standalone.py"
echo ""
echo "✅ 准备完成！按顺序启动各终端 / Ready! Start terminals in order"
echo ""
echo "🔧 故障注入示例 / Fault Injection Examples:"
echo "   inject 1 0 10        → 推进器0完全失效10秒 / Thruster 0 complete failure 10s"
echo "   inject 2 0,1,2 15    → 推进器0,1,2部分失效15秒 / Thrusters 0,1,2 partial failure 15s"
echo "   inject 3 5 8         → 推进器5卡死8秒 / Thruster 5 stuck 8s"
echo "   inject 4 6 10        → 推进器6推力反向10秒 / Thruster 6 reversed 10s"
echo "   clear               → 清除故障 / Clear all faults"
echo ""
